/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password while signed in
         * @description Verify the old password, write the new hash, revoke siblings.
         *
         *     Per ``auth.md``: revokes every session **other than** the one the
         *     request came from — the user keeps their cookie.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password-reset email (no-enumeration)
         * @description Always returns 202. Mints + emails a token only if the email exists.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a session cookie
         * @description Issue a session cookie when credentials are valid; ``400`` otherwise.
         *
         *     The 400 is shape-identical for ``no-such-email`` and
         *     ``wrong-password`` so the response cannot enumerate addresses.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session
         * @description Revoke the session row backing the current cookie and clear it.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-everywhere": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke every session for the current user
         * @description Revoke every live session for the caller and clear their cookie.
         */
        post: operations["logout_everywhere_api_v1_auth_logout_everywhere_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current user + their memberships
         * @description Return the signed-in user and the workspaces they belong to.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-mail a verification token (no-enumeration)
         * @description Re-mail a verification token. Always returns 202.
         *
         *     Resolves the target email from the session cookie when present,
         *     falling back to the body. Silent on every error path (unknown
         *     email, already-verified, rate-limit) — the user-facing copy on
         *     the page acknowledges the request without confirming the address.
         */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume a password-reset token + set a new password
         * @description Set a new password and revoke every session for the user.
         *
         *     Per ``auth.md`` state machine, a successful reset revokes
         *     **every** session (including the active one) — the assumption is
         *     account compromise; the user logs in fresh.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new account + first workspace
         * @description Create user + workspace + owner membership atomically.
         *
         *     No-enumeration: a duplicate email returns the *same* 201 shape and
         *     triggers the ``verification_already`` email rather than the
         *     verification email. The two response bodies are byte-equivalent
         *     apart from row ids that already existed.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume an email-verification token
         * @description Flip ``users.is_verified=true`` if the token is live, else 410.
         */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return dashboard KPI and intake summary
         * @description Return dashboard summary data for the active workspace.
         */
        get: operations["get_dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feedback items in the workspace
         * @description Return a paginated, filtered envelope of feedback in this workspace.
         */
        get: operations["list_feedback_api_v1_feedback_get"];
        put?: never;
        /**
         * Create a feedback item (authenticated team submission)
         * @description Insert a new feedback item scoped to the caller's workspace.
         */
        post: operations["create_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one feedback item
         * @description Return a single feedback item, scoped to the workspace.
         */
        get: operations["get_feedback_api_v1_feedback__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a feedback item
         * @description Hard-delete a feedback item; cascades to tags + notes.
         */
        delete: operations["delete_feedback_api_v1_feedback__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Partially update a feedback item
         * @description Apply a partial update; missing fields are left untouched.
         */
        patch: operations["patch_feedback_api_v1_feedback__item_id__patch"];
        trace?: never;
    };
    "/api/v1/feedback/{item_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List internal notes for a feedback item
         * @description Return notes ordered oldest-first (timeline order).
         */
        get: operations["list_notes_api_v1_feedback__item_id__notes_get"];
        put?: never;
        /**
         * Add an internal note to a feedback item
         * @description Append an internal note authored by the current user.
         */
        post: operations["create_note_api_v1_feedback__item_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{item_id}/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a note (author or workspace owner)
         * @description Delete an internal note; allowed to its author or the workspace owner.
         */
        delete: operations["delete_note_api_v1_feedback__item_id__notes__note_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit an internal note (author + 15-minute window)
         * @description Edit a note's body within 15 minutes of creation, by the author.
         */
        patch: operations["patch_note_api_v1_feedback__item_id__notes__note_id__patch"];
        trace?: never;
    };
    "/api/v1/feedback/{item_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the tag set on a feedback item
         * @description Replace ``feedback_tags`` rows for ``item_id``.
         *
         *     Every requested tag must belong to the same workspace as the
         *     feedback item; cross-tenant tag ids 404 (not 400) so the response
         *     cannot be used to enumerate tag ids in another workspace.
         */
        post: operations["replace_feedback_tags_api_v1_feedback__item_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/frontend-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest frontend telemetry event
         * @description Accept and log one frontend telemetry event.
         *
         *     The endpoint is intentionally fail-soft: events are best effort and
         *     must never block the user-facing request path.
         */
        post: operations["ingest_frontend_event_api_v1_frontend_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a workspace invitation
         * @description Consume an invitation token; create the membership.
         *
         *     All non-OK token states (unknown, expired, consumed, revoked) map
         *     to ``410 Gone`` per ``auth.md`` — Token TTLs.
         */
        post: operations["accept_invitation_api_v1_invitations__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/feedback/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Public, unauthenticated feedback submission
         * @description Create a feedback item from an anonymous public submitter.
         */
        post: operations["submit_public_feedback_api_v1_public_feedback__slug__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submitters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List submitters
         * @description Return submitters; ``q`` matches name and email (case-insensitive).
         */
        get: operations["list_submitters_api_v1_submitters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submitters/{submitter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one submitter
         * @description Return a single submitter scoped to the workspace.
         */
        get: operations["get_submitter_api_v1_submitters__submitter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit submitter name / internal notes
         * @description Apply a partial update; only ``name`` and ``internal_notes`` are writable.
         */
        patch: operations["patch_submitter_api_v1_submitters__submitter_id__patch"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tags
         * @description Return all tags in the workspace, ordered by name.
         */
        get: operations["list_tags_api_v1_tags_get"];
        put?: never;
        /**
         * Create a tag (owner only)
         * @description Create a workspace-scoped tag.
         *
         *     Returns ``409`` with ``code=tag_slug_taken`` on slug collisions
         *     rather than letting the unique-constraint IntegrityError bubble
         *     to the generic 500 handler.
         */
        post: operations["create_tag_api_v1_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a tag (owner only); cascades to feedback_tags
         * @description Delete a tag; the FK cascade removes its ``feedback_tags`` rows.
         */
        delete: operations["delete_tag_api_v1_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename or recolour a tag (owner only)
         * @description Apply a partial update to a tag.
         */
        patch: operations["patch_tag_api_v1_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current user's preferences
         * @description Apply a partial preferences update to the current user.
         *
         *     The transaction boundary lives in :func:`get_db`; this handler
         *     only stages the change and flushes so the response can quote
         *     the post-update value back.
         */
        patch: operations["patch_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's workspaces
         * @description Return one entry per workspace the caller has a membership for.
         */
        get: operations["list_my_workspaces_api_v1_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one workspace
         * @description Return the workspace identified by ``slug`` in the URL.
         */
        get: operations["get_workspace_api_v1_workspaces__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update workspace settings (owner only)
         * @description Update mutable workspace fields.
         *
         *     ``slug`` is immutable (rejected by the request schema). Both
         *     ``name`` and ``public_submit_enabled`` are optional but the body
         *     must contain at least one of them.
         */
        patch: operations["update_workspace_api_v1_workspaces__slug__patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{slug}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List open invitations for a workspace (owner only)
         * @description Return every not-yet-accepted, not-yet-revoked invitation.
         */
        get: operations["list_invitations_api_v1_workspaces__slug__invitations_get"];
        put?: never;
        /**
         * Invite a user to the workspace (owner only)
         * @description Mint an invitation token, persist the row, and send the email.
         *
         *     Re-inviting an email that already has an open invitation revokes
         *     the prior row first ("revoke + mint" — the partial unique index
         *     ``workspace_invitations_open_idx`` enforces at-most-one-open).
         */
        post: operations["create_invitation_api_v1_workspaces__slug__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{slug}/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an open invitation (owner only)
         * @description Mark an invitation revoked.
         *
         *     Cross-tenant probes are already 404'd by ``WorkspaceContextDep``;
         *     this handler additionally 404s if the id belongs to a *different*
         *     workspace's invitation, so an owner cannot probe other workspaces
         *     by feeding random ids into their own slug.
         */
        delete: operations["revoke_invitation_route_api_v1_workspaces__slug__invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members of a workspace
         * @description Return every member of the workspace plus their role.
         */
        get: operations["list_members_api_v1_workspaces__slug__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{slug}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member from a workspace (owner only)
         * @description Delete a membership row.
         *
         *     - ``404`` if no such membership in this workspace.
         *     - ``409`` if the target is the last owner.
         *     - ``409`` if the caller tries to remove themselves (forces the
         *       caller to promote a co-owner first; documented in api.md).
         */
        delete: operations["remove_member_route_api_v1_workspaces__slug__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return ``{"status": "ok"}`` without touching the database.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Verify the database is reachable within a 2-second budget.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChangePasswordRequest
         * @description ``POST /api/v1/auth/change-password`` body.
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * DashboardCountsResponse
         * @description Top-level KPI counts for the current workspace.
         */
        DashboardCountsResponse: {
            /** High Pain Signals */
            high_pain_signals: number;
            /** Needs Action */
            needs_action: number;
            /** Total Signals */
            total_signals: number;
        };
        /**
         * DashboardIntakePointResponse
         * @description One intake-series point in the current 30-day window.
         */
        DashboardIntakePointResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Received */
            received: number;
        };
        /**
         * DashboardSummaryResponse
         * @description Response envelope for ``GET /api/v1/dashboard/summary``.
         */
        DashboardSummaryResponse: {
            counts: components["schemas"]["DashboardCountsResponse"];
            /** Intake 30D */
            intake_30d: components["schemas"]["DashboardIntakePointResponse"][];
            total_signals_widget: components["schemas"]["DashboardTotalSignalsWidgetResponse"];
        };
        /**
         * DashboardTotalSignalsWidgetResponse
         * @description Display contract payload for the Total signals widget.
         */
        DashboardTotalSignalsWidgetResponse: {
            /** Comparison Label */
            comparison_label: string;
            /**
             * Delta Direction
             * @enum {string}
             */
            delta_direction: "up" | "down" | "flat";
            /** Delta Pct */
            delta_pct: number;
            /**
             * Label
             * @default Total signals
             * @constant
             */
            label: "Total signals";
            /** Sparkline Date Labels */
            sparkline_date_labels: string[];
            /** Sparkline Points */
            sparkline_points: number[];
            /** Value */
            value: number;
            /**
             * Widget Id
             * @default kpi-total-signals
             * @constant
             */
            widget_id: "kpi-total-signals";
        };
        /**
         * FeedbackCreateV2
         * @description Payload for ``POST /api/v1/feedback`` (workspace-scoped).
         */
        FeedbackCreateV2: {
            /** Assignee User Id */
            assignee_user_id?: string | null;
            /** Description */
            description?: string | null;
            /** Pain Level */
            pain_level: number;
            priority?: components["schemas"]["Priority"] | null;
            source: components["schemas"]["Source"];
            /** Source Other */
            source_other?: string | null;
            /** @default new */
            status: components["schemas"]["Status"];
            /** Title */
            title: string;
            /** @default other */
            type: components["schemas"]["FeedbackType"];
            /** Type Other */
            type_other?: string | null;
        };
        /**
         * FeedbackListEnvelopeV2
         * @description Paginated envelope for ``GET /api/v1/feedback``.
         */
        FeedbackListEnvelopeV2: {
            /** Items */
            items: components["schemas"]["FeedbackResponseV2"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * FeedbackResponseV2
         * @description Outbound representation of a v2 feedback item.
         */
        FeedbackResponseV2: {
            /** Assignee User Id */
            assignee_user_id: string | null;
            /** Created At */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Pain Level */
            pain_level: number;
            priority: components["schemas"]["Priority"] | null;
            /** Published To Changelog */
            published_to_changelog: boolean;
            /** Published To Roadmap */
            published_to_roadmap: boolean;
            /** Release Note */
            release_note: string | null;
            source: components["schemas"]["Source"];
            /** Source Other */
            source_other: string | null;
            status: components["schemas"]["Status"];
            /** Submitter Id */
            submitter_id: string | null;
            /** Title */
            title: string;
            type: components["schemas"]["FeedbackType"];
            /** Type Other */
            type_other: string | null;
            /** Updated At */
            updated_at: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * FeedbackTagsReplaceRequest
         * @description Payload for ``POST /api/v1/feedback/{id}/tags``.
         */
        FeedbackTagsReplaceRequest: {
            /** Tag Ids */
            tag_ids: string[];
        };
        /**
         * FeedbackType
         * @description Classification of a feedback item.
         *
         *     Values match ``type_enum`` in
         *     ``docs/project/spec/v2/schema.md``. Stored on
         *     ``feedback_item.type``; ``other`` requires a non-null
         *     ``type_other`` free-text field (DB ``CHECK`` constraint).
         * @enum {string}
         */
        FeedbackType: "bug" | "feature_request" | "complaint" | "praise" | "question" | "other";
        /**
         * FeedbackUpdateV2
         * @description Partial-update payload for ``PATCH /api/v1/feedback/{id}``.
         */
        FeedbackUpdateV2: {
            /** Assignee User Id */
            assignee_user_id?: string | null;
            /** Description */
            description?: string | null;
            /** Pain Level */
            pain_level?: number | null;
            priority?: components["schemas"]["Priority"] | null;
            /** Published To Changelog */
            published_to_changelog?: boolean | null;
            /** Published To Roadmap */
            published_to_roadmap?: boolean | null;
            /** Release Note */
            release_note?: string | null;
            source?: components["schemas"]["Source"] | null;
            /** Source Other */
            source_other?: string | null;
            status?: components["schemas"]["Status"] | null;
            /** Title */
            title?: string | null;
            type?: components["schemas"]["FeedbackType"] | null;
            /** Type Other */
            type_other?: string | null;
        };
        /**
         * ForgotPasswordRequest
         * @description ``POST /api/v1/auth/forgot-password`` body.
         */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * FrontendEventRequest
         * @description Client-side telemetry payload emitted by React pages.
         */
        FrontendEventRequest: {
            /** Client Release */
            client_release: string;
            /** Code */
            code?: string | null;
            /**
             * Event
             * @enum {string}
             */
            event: "api_failure" | "mutation_failure" | "window_error" | "unhandled_rejection";
            /** Message */
            message?: string | null;
            /** Method */
            method?: string | null;
            /** Path */
            path?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Route */
            route: string;
            /** Status Code */
            status_code?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvitationAcceptResponse
         * @description ``POST /api/v1/invitations/{token}/accept`` 200 body.
         */
        InvitationAcceptResponse: {
            role: components["schemas"]["WorkspaceRole"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string;
            /** Workspace Slug */
            workspace_slug: string;
        };
        /**
         * InvitationCreateRequest
         * @description ``POST /api/v1/workspaces/{slug}/invitations`` body.
         */
        InvitationCreateRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default team_member */
            role: components["schemas"]["WorkspaceRole"];
        };
        /**
         * InvitationListResponse
         * @description ``GET /api/v1/workspaces/{slug}/invitations`` 200 body.
         */
        InvitationListResponse: {
            /** Items */
            items: components["schemas"]["InvitationResponse"][];
            /** Total */
            total: number;
        };
        /**
         * InvitationResponse
         * @description One workspace invitation row, sans ``token_hash``.
         *
         *     The raw token is **only** delivered via email; the JSON surface
         *     never echoes it. An attacker with read access to invitation
         *     listings must not be able to accept the invite.
         */
        InvitationResponse: {
            /** Accepted At */
            accepted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Invited By Id
             * Format: uuid
             */
            invited_by_id: string;
            /** Revoked At */
            revoked_at: string | null;
            role: components["schemas"]["WorkspaceRole"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * LoginRequest
         * @description ``POST /api/v1/auth/login`` body.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description ``POST /api/v1/auth/login`` 200 body.
         */
        LoginResponse: {
            /** Memberships */
            memberships: components["schemas"]["MembershipResponse"][];
            user: components["schemas"]["UserResponse"];
        };
        /**
         * MeResponse
         * @description ``GET /api/v1/auth/me`` 200 body.
         */
        MeResponse: {
            /** Memberships */
            memberships: components["schemas"]["MembershipResponse"][];
            user: components["schemas"]["UserResponse"];
        };
        /**
         * MemberListResponse
         * @description ``GET /api/v1/workspaces/{slug}/members`` 200 body.
         */
        MemberListResponse: {
            /** Items */
            items: components["schemas"]["MemberResponse"][];
            /** Total */
            total: number;
        };
        /**
         * MemberResponse
         * @description One member of a workspace.
         */
        MemberResponse: {
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            role: components["schemas"]["WorkspaceRole"];
            user: components["schemas"]["MemberUserResponse"];
        };
        /**
         * MemberUserResponse
         * @description User shape inside a member listing.
         *
         *     A subset of :class:`feedback_triage.auth.schemas.UserResponse` — we
         *     deliberately drop ``is_verified`` because surfacing another
         *     workspace member's verification state would be a small information
         *     leak with no UI use case in v2.0.
         */
        MemberUserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * MembershipResponse
         * @description One workspace the caller belongs to + their role.
         */
        MembershipResponse: {
            role: components["schemas"]["WorkspaceRole"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string;
            /** Workspace Slug */
            workspace_slug: string;
        };
        /**
         * NoteCreateRequest
         * @description Payload for ``POST /api/v1/feedback/{id}/notes``.
         */
        NoteCreateRequest: {
            /** Body */
            body: string;
        };
        /**
         * NoteListEnvelope
         * @description Paginated envelope for ``GET /api/v1/feedback/{id}/notes``.
         */
        NoteListEnvelope: {
            /** Items */
            items: components["schemas"]["NoteResponse"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * NoteResponse
         * @description Outbound representation of an internal feedback note.
         */
        NoteResponse: {
            /**
             * Author User Id
             * Format: uuid
             */
            author_user_id: string;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /** Feedback Id */
            feedback_id: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * NoteUpdateRequest
         * @description Payload for ``PATCH /api/v1/feedback/{id}/notes/{note_id}``.
         */
        NoteUpdateRequest: {
            /** Body */
            body: string;
        };
        /**
         * Priority
         * @description Priority assigned by the team during triage.
         *
         *     Values match ``priority_enum`` in
         *     ``docs/project/spec/v2/schema.md``. Stored on
         *     ``feedback_item.priority`` (nullable until set).
         * @enum {string}
         */
        Priority: "low" | "medium" | "high" | "critical";
        /**
         * PublicFeedbackCreate
         * @description Request body for ``POST /api/v1/public/feedback/{slug}``.
         *
         *     Note ``website`` -- the honeypot. A legitimate browser submission
         *     leaves it untouched; bots that auto-fill every visible input
         *     will populate it and trip the silent-discard branch.
         */
        PublicFeedbackCreate: {
            /** Description */
            description?: string | null;
            /** Pain Level */
            pain_level: number;
            /** @default web_form */
            source: components["schemas"]["Source"];
            /** Source Other */
            source_other?: string | null;
            /** Submitter Email */
            submitter_email?: string | null;
            /** Submitter Name */
            submitter_name?: string | null;
            /** Title */
            title: string;
            /** @default other */
            type: components["schemas"]["FeedbackType"];
            /** Type Other */
            type_other?: string | null;
            /**
             * Website
             * @default
             */
            website: string;
        };
        /**
         * ResendVerificationRequest
         * @description ``POST /api/v1/auth/resend-verification`` body.
         *
         *     Either an ``email`` is provided (anonymous re-request) or the
         *     request is authenticated; the route handles both shapes.
         */
        ResendVerificationRequest: {
            /** Email */
            email?: string | null;
        };
        /**
         * ResetPasswordRequest
         * @description ``POST /api/v1/auth/reset-password`` body.
         */
        ResetPasswordRequest: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /**
         * SignupRequest
         * @description ``POST /api/v1/auth/signup`` body.
         */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Workspace Name */
            workspace_name?: string | null;
        };
        /**
         * SignupResponse
         * @description ``POST /api/v1/auth/signup`` 201 body.
         *
         *     The shape is identical for fresh and duplicate signups so the
         *     response cannot be used to enumerate accounts (``auth.md`` —
         *     Email enumeration posture).
         */
        SignupResponse: {
            user: components["schemas"]["UserResponse"];
            workspace: components["schemas"]["WorkspaceResponse"];
        };
        /**
         * Source
         * @description Where a feedback item originated.
         * @enum {string}
         */
        Source: "email" | "interview" | "reddit" | "support" | "app_store" | "twitter" | "web_form" | "other";
        /**
         * Status
         * @description Triage state of a feedback item.
         *
         *     The v2.0 workflow adds ``needs_info``, ``accepted``, ``in_progress``,
         *     ``shipped``, ``closed``, and ``spam`` (per ADR 063). ``rejected``
         *     is retained as an enum label only because Postgres has no
         *     ``ALTER TYPE … DROP VALUE`` in stable releases; a ``CHECK`` added
         *     in Migration B forbids the application from writing it, and the
         *     backfill rewrites every legacy row to ``closed``.
         * @enum {string}
         */
        Status: "new" | "needs_info" | "reviewing" | "accepted" | "planned" | "in_progress" | "shipped" | "closed" | "spam" | "rejected";
        /**
         * SubmitterListEnvelope
         * @description Paginated envelope for ``GET /api/v1/submitters``.
         */
        SubmitterListEnvelope: {
            /** Items */
            items: components["schemas"]["SubmitterResponse"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * SubmitterResponse
         * @description Outbound representation of a submitter.
         */
        SubmitterResponse: {
            /** Created At */
            created_at: string;
            /** Email */
            email: string | null;
            /** First Seen At */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Internal Notes */
            internal_notes: string | null;
            /** Last Seen At */
            last_seen_at: string;
            /** Name */
            name: string | null;
            /** Submission Count */
            submission_count: number;
            /** Updated At */
            updated_at: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * SubmitterUpdateRequest
         * @description Payload for ``PATCH /api/v1/submitters/{id}``.
         */
        SubmitterUpdateRequest: {
            /** Internal Notes */
            internal_notes?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * TagCreateRequest
         * @description Payload for ``POST /api/v1/tags``.
         */
        TagCreateRequest: {
            /**
             * Color
             * @default slate
             * @enum {string}
             */
            color: "slate" | "teal" | "amber" | "rose" | "indigo" | "sky" | "green" | "violet";
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * TagListEnvelope
         * @description Paginated envelope for ``GET /api/v1/tags``.
         */
        TagListEnvelope: {
            /** Items */
            items: components["schemas"]["TagResponse"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * TagResponse
         * @description Outbound representation of a tag.
         */
        TagResponse: {
            /** Color */
            color: string;
            /** Created At */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * TagUpdateRequest
         * @description Payload for ``PATCH /api/v1/tags/{id}``.
         */
        TagUpdateRequest: {
            /** Color */
            color?: ("slate" | "teal" | "amber" | "rose" | "indigo" | "sky" | "green" | "violet") | null;
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /**
         * UserPreferencesUpdate
         * @description Partial-update payload for :func:`patch_me`.
         *
         *     Every field is optional; missing fields leave the column
         *     untouched. New preferences may be added in subsequent PRs without
         *     breaking older clients.
         */
        UserPreferencesUpdate: {
            /** Theme Preference */
            theme_preference?: ("light" | "dark" | "system") | null;
        };
        /**
         * UserResponse
         * @description User shape returned by signup / login / me.
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Verified */
            is_verified: boolean;
            role: components["schemas"]["UserRole"];
            /** Theme Preference */
            theme_preference: string;
        };
        /**
         * UserRole
         * @description Site-wide role on the ``users`` table.
         *
         *     Values match ``user_role_enum`` in
         *     ``docs/project/spec/v2/schema.md``. Distinct from
         *     :class:`WorkspaceRole`, which scopes a user's privileges inside a
         *     single workspace via the ``memberships`` table. See ADR 060 and
         *     ``docs/project/spec/v2/multi-tenancy.md``.
         * @enum {string}
         */
        UserRole: "admin" | "team_member" | "demo";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerifyEmailRequest
         * @description ``POST /api/v1/auth/verify-email`` body.
         */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
        /**
         * WorkspaceResponse
         * @description Workspace shape returned by signup.
         */
        WorkspaceResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Demo */
            is_demo: boolean;
            /** Name */
            name: string;
            /** Public Submit Enabled */
            public_submit_enabled: boolean;
            /** Slug */
            slug: string;
        };
        /**
         * WorkspaceRole
         * @description Per-workspace role stored on ``memberships.role``.
         *
         *     Values match ``workspace_role_enum`` in ADR 060 and
         *     ``docs/project/spec/v2/schema.md``.
         * @enum {string}
         */
        WorkspaceRole: "owner" | "team_member";
        /**
         * WorkspaceUpdateRequest
         * @description ``PATCH /api/v1/workspaces/{slug}`` body.
         *
         *     ``slug`` is intentionally absent: per the v2.0 glossary the slug is
         *     immutable. ``name`` and ``public_submit_enabled`` are both
         *     optional; at least one must be supplied (the route returns 422
         *     otherwise). Explicit JSON ``null`` is rejected for both fields
         *     because the underlying columns are ``NOT NULL`` -- omit a field
         *     to leave it unchanged instead.
         */
        WorkspaceUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Public Submit Enabled */
            public_submit_enabled?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_everywhere_api_v1_auth_logout_everywhere_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_api_v1_feedback_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number | null;
                status?: components["schemas"]["Status"] | null;
                source?: components["schemas"]["Source"] | null;
                type?: components["schemas"]["FeedbackType"] | null;
                priority?: components["schemas"]["Priority"] | null;
                tag?: string | null;
                submitter_id?: string | null;
                assignee_user_id?: string | null;
                q?: string | null;
                published_to_roadmap?: boolean | null;
                published_to_changelog?: boolean | null;
                created_after?: string | null;
                created_before?: string | null;
                stale?: boolean | null;
                sort_by?: string;
            };
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackListEnvelopeV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreateV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_api_v1_feedback__item_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feedback_api_v1_feedback__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_feedback_api_v1_feedback__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackUpdateV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_api_v1_feedback__item_id__notes_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number | null;
            };
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteListEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_v1_feedback__item_id__notes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v1_feedback__item_id__notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
                note_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_note_api_v1_feedback__item_id__notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
                note_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_feedback_tags_api_v1_feedback__item_id__tags_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackTagsReplaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_frontend_event_api_v1_frontend_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrontendEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_invitations__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAcceptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_public_feedback_api_v1_public_feedback__slug__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicFeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submitters_api_v1_submitters_get: {
        parameters: {
            query?: {
                q?: string | null;
                skip?: number;
                limit?: number | null;
            };
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitterListEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submitter_api_v1_submitters__submitter_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                submitter_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_submitter_api_v1_submitters__submitter_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                submitter_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitterUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_v1_tags_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number | null;
            };
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_api_v1_tags_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_v1_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                tag_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tag_api_v1_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                tag_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_workspaces_api_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_workspaces__slug__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workspace_api_v1_workspaces__slug__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invitations_api_v1_workspaces__slug__invitations_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_workspaces__slug__invitations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_route_api_v1_workspaces__slug__invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                invitation_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_workspaces__slug__members_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path?: never;
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_route_api_v1_workspaces__slug__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Workspace-Slug"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                signalnest_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
