"""Create feedback_item table, source/status enums, indexes, and updated_at trigger.

Revision ID: 0001
Revises:
Create Date: 2026-04-28

Hand-authored (not autogenerated). Mirrors the canonical schema in
``docs/project/spec/spec-v1.md`` — PostgreSQL Specification.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SOURCE_VALUES = (
    "email",
    "interview",
    "reddit",
    "support",
    "app_store",
    "twitter",
    "other",
)
STATUS_VALUES = ("new", "reviewing", "planned", "rejected")


def upgrade() -> None:
    source_enum = postgresql.ENUM(*SOURCE_VALUES, name="source_enum")
    status_enum = postgresql.ENUM(*STATUS_VALUES, name="status_enum")
    bind = op.get_bind()
    source_enum.create(bind, checkfirst=False)
    status_enum.create(bind, checkfirst=False)

    op.create_table(
        "feedback_item",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source",
            postgresql.ENUM(name="source_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("pain_level", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="status_enum", create_type=False),
            nullable=False,
            server_default=sa.text("'new'::status_enum"),
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "pain_level BETWEEN 1 AND 5",
            name="feedback_item_pain_level_range",
        ),
        sa.CheckConstraint(
            "length(btrim(title)) > 0",
            name="feedback_item_title_not_blank",
        ),
        sa.CheckConstraint(
            "length(title) <= 200",
            name="feedback_item_title_max_len",
        ),
        sa.CheckConstraint(
            "description IS NULL OR length(description) <= 5000",
            name="feedback_item_description_max_len",
        ),
    )

    op.create_index(
        "ix_feedback_item_created_at_desc",
        "feedback_item",
        [sa.text("created_at DESC")],
    )
    op.create_index("ix_feedback_item_status", "feedback_item", ["status"])
    op.create_index("ix_feedback_item_source", "feedback_item", ["source"])

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at := now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER feedback_item_set_updated_at
            BEFORE UPDATE ON feedback_item
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS feedback_item_set_updated_at ON feedback_item;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    op.drop_index("ix_feedback_item_source", table_name="feedback_item")
    op.drop_index("ix_feedback_item_status", table_name="feedback_item")
    op.drop_index("ix_feedback_item_created_at_desc", table_name="feedback_item")
    op.drop_table("feedback_item")
    bind = op.get_bind()
    postgresql.ENUM(name="status_enum").drop(bind, checkfirst=False)
    postgresql.ENUM(name="source_enum").drop(bind, checkfirst=False)
