"""v2 Migration A — auth, tenancy, email_log tables + native enums.

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-05

Hand-authored (not autogenerated). The single largest schema migration
in the v1→v2 jump. Mirrors the canonical schema in
``docs/project/spec/v2/schema.md`` and the choreography in
[ADR 062](../../docs/adr/062-v1-to-v2-data-migration.md).

Migration A is **schema-only and additive**. It:

1. enables ``citext`` (case-insensitive emails / slugs);
2. creates four new native Postgres enum types
   (``user_role_enum``, ``workspace_role_enum``, ``email_status_enum``,
   ``email_purpose_enum``);
3. extends ``status_enum`` with the new v2 values
   (``needs_info``, ``accepted``, ``in_progress``, ``shipped``,
   ``closed``, ``spam``) — each ``ALTER TYPE … ADD VALUE`` runs in
   its own ``autocommit_block`` per Postgres's "non-transactional
   enum changes" rule;
4. extends ``source_enum`` with ``web_form``;
5. creates the auth + tenancy + email_log tables;
6. inserts the synthetic ``legacy`` admin user and the
   ``signalnest-legacy`` workspace (per ADR 062);
7. adds ``feedback_item.workspace_id`` as a nullable column.

Migration B (PR 2.1) backfills ``feedback_item.workspace_id``, flips
it to ``NOT NULL``, renames ``rejected`` → ``closed``, and creates the
v2 indexes on ``feedback_item``. Migration A and Migration B together
satisfy the v1.0 → v2.0 data-migration contract; A is reversible
(``downgrade()`` works), B intentionally is not.

Hand-review checklist (verified before merge):

- every table has a native enum where the spec calls for one;
- every text column has a ``CHECK length(...) <= N``;
- every FK has explicit ``ON DELETE`` semantics;
- every ``updated_at`` column has a ``BEFORE UPDATE`` trigger that
  reuses the project-wide ``set_updated_at()`` plpgsql function.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Sentinel password hash for the synthetic legacy admin. Not a valid
# Argon2id encoded hash (no ``$argon2id$`` prefix, wrong segment count),
# so the verifier will reject every login attempt by construction.
# See ADR 062 — "password hash set to a sentinel that no real Argon2id
# verifier will accept (login disabled)".
LEGACY_ADMIN_PASSWORD_SENTINEL = "!disabled-legacy-v1-admin!"  # nosec B105 - sentinel, intentionally not a valid hash

USER_ROLE_VALUES = ("admin", "team_member", "demo")
WORKSPACE_ROLE_VALUES = ("owner", "team_member")
EMAIL_STATUS_VALUES = ("queued", "sent", "retrying", "failed")
EMAIL_PURPOSE_VALUES = (
    "verification",
    "password_reset",
    "invitation",
    "status_change",
)

NEW_STATUS_VALUES = (
    "needs_info",
    "accepted",
    "in_progress",
    "shipped",
    "closed",
    "spam",
)
NEW_SOURCE_VALUES = ("web_form",)


def _create_updated_at_trigger(table: str) -> None:
    """Attach the project-wide ``set_updated_at()`` BEFORE UPDATE trigger.

    The plpgsql function ``set_updated_at`` was created by Migration
    0001 and is reused unchanged here — every v2 table with an
    ``updated_at`` column gets the same trigger.
    """
    op.execute(
        f"""
        CREATE TRIGGER {table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. Extensions
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ------------------------------------------------------------------
    # 2. New native enum types
    # ------------------------------------------------------------------
    bind = op.get_bind()
    postgresql.ENUM(*USER_ROLE_VALUES, name="user_role_enum").create(
        bind, checkfirst=False
    )
    postgresql.ENUM(*WORKSPACE_ROLE_VALUES, name="workspace_role_enum").create(
        bind, checkfirst=False
    )
    postgresql.ENUM(*EMAIL_STATUS_VALUES, name="email_status_enum").create(
        bind, checkfirst=False
    )
    postgresql.ENUM(*EMAIL_PURPOSE_VALUES, name="email_purpose_enum").create(
        bind, checkfirst=False
    )

    # ------------------------------------------------------------------
    # 3. Extend the v1 enums.
    #
    # ``ALTER TYPE … ADD VALUE`` cannot run inside the migration's
    # outer transaction; each new label is added in its own
    # autocommit block per Alembic's documented pattern.
    # ------------------------------------------------------------------
    for value in NEW_STATUS_VALUES:
        with op.get_context().autocommit_block():
            op.execute(f"ALTER TYPE status_enum ADD VALUE IF NOT EXISTS '{value}'")
    for value in NEW_SOURCE_VALUES:
        with op.get_context().autocommit_block():
            op.execute(f"ALTER TYPE source_enum ADD VALUE IF NOT EXISTS '{value}'")

    user_role_enum = postgresql.ENUM(name="user_role_enum", create_type=False)
    workspace_role_enum = postgresql.ENUM(name="workspace_role_enum", create_type=False)
    email_status_enum = postgresql.ENUM(name="email_status_enum", create_type=False)
    email_purpose_enum = postgresql.ENUM(name="email_purpose_enum", create_type=False)

    citext = postgresql.CITEXT()

    # ------------------------------------------------------------------
    # 4. users
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", citext, nullable=False, unique=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "role",
            user_role_enum,
            nullable=False,
            server_default=sa.text("'team_member'::user_role_enum"),
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(email) <= 320",
            name="users_email_max_len",
        ),
        sa.CheckConstraint(
            "length(password_hash) <= 256",
            name="users_password_hash_max_len",
        ),
    )
    _create_updated_at_trigger("users")

    # ------------------------------------------------------------------
    # 5. workspaces
    # ------------------------------------------------------------------
    op.create_table(
        "workspaces",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("slug", citext, nullable=False, unique=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "owner_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "is_demo",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$'",
            name="workspaces_slug_format",
        ),
        sa.CheckConstraint(
            "length(name) BETWEEN 1 AND 60",
            name="workspaces_name_len",
        ),
    )
    _create_updated_at_trigger("workspaces")

    # ------------------------------------------------------------------
    # 6. workspace_memberships
    # ------------------------------------------------------------------
    op.create_table(
        "workspace_memberships",
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
            nullable=False,
        ),
        sa.Column("role", workspace_role_enum, nullable=False),
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # ------------------------------------------------------------------
    # 7. workspace_invitations
    # ------------------------------------------------------------------
    op.create_table(
        "workspace_invitations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", citext, nullable=False),
        sa.Column(
            "role",
            workspace_role_enum,
            nullable=False,
            server_default=sa.text("'team_member'::workspace_role_enum"),
        ),
        sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
        sa.Column(
            "invited_by_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "accepted_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(email) <= 320",
            name="workspace_invitations_email_max_len",
        ),
        sa.CheckConstraint(
            "length(token_hash) <= 256",
            name="workspace_invitations_token_hash_max_len",
        ),
    )
    op.create_index(
        "workspace_invitations_open_idx",
        "workspace_invitations",
        ["workspace_id", "email"],
        unique=True,
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )

    # ------------------------------------------------------------------
    # 8. sessions
    # ------------------------------------------------------------------
    op.create_table(
        "sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_inet", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_seen_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "length(token_hash) <= 256",
            name="sessions_token_hash_max_len",
        ),
        sa.CheckConstraint(
            "user_agent IS NULL OR length(user_agent) <= 512",
            name="sessions_user_agent_max_len",
        ),
    )
    op.create_index(
        "sessions_token_hash_idx",
        "sessions",
        ["token_hash"],
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "sessions_user_id_idx",
        "sessions",
        ["user_id"],
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    # ------------------------------------------------------------------
    # 9. email_verification_tokens
    # ------------------------------------------------------------------
    op.create_table(
        "email_verification_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "consumed_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(token_hash) <= 256",
            name="email_verification_tokens_token_hash_max_len",
        ),
    )

    # ------------------------------------------------------------------
    # 10. password_reset_tokens
    # ------------------------------------------------------------------
    op.create_table(
        "password_reset_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "consumed_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(token_hash) <= 256",
            name="password_reset_tokens_token_hash_max_len",
        ),
    )

    # ------------------------------------------------------------------
    # 11. auth_rate_limits
    # ------------------------------------------------------------------
    op.create_table(
        "auth_rate_limits",
        sa.Column("bucket_key", sa.Text(), primary_key=True, nullable=False),
        sa.Column(
            "window_start",
            postgresql.TIMESTAMP(timezone=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "count",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.CheckConstraint(
            "length(bucket_key) <= 128",
            name="auth_rate_limits_bucket_key_max_len",
        ),
        sa.CheckConstraint(
            "count >= 0",
            name="auth_rate_limits_count_nonneg",
        ),
    )

    # ------------------------------------------------------------------
    # 12. email_log (per ADR 061)
    # ------------------------------------------------------------------
    op.create_table(
        "email_log",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("to_address", sa.Text(), nullable=False),
        sa.Column("purpose", email_purpose_enum, nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column(
            "status",
            email_status_enum,
            nullable=False,
            server_default=sa.text("'queued'::email_status_enum"),
        ),
        sa.Column("provider_id", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "attempt_count",
            sa.SmallInteger(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(to_address) <= 320",
            name="email_log_to_address_max_len",
        ),
        sa.CheckConstraint(
            "length(template) <= 64",
            name="email_log_template_max_len",
        ),
        sa.CheckConstraint(
            "length(subject) <= 256",
            name="email_log_subject_max_len",
        ),
        sa.CheckConstraint(
            "provider_id IS NULL OR length(provider_id) <= 128",
            name="email_log_provider_id_max_len",
        ),
        sa.CheckConstraint(
            "error_code IS NULL OR length(error_code) <= 64",
            name="email_log_error_code_max_len",
        ),
        sa.CheckConstraint(
            "error_detail IS NULL OR length(error_detail) <= 1024",
            name="email_log_error_detail_max_len",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name="email_log_attempt_count_nonneg",
        ),
    )
    _create_updated_at_trigger("email_log")
    op.create_index(
        "email_log_workspace_idx",
        "email_log",
        ["workspace_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "email_log_status_idx",
        "email_log",
        ["status", sa.text("created_at DESC")],
        postgresql_where=sa.text("status IN ('queued', 'retrying', 'failed')"),
    )
    op.create_index(
        "email_log_purpose_idx",
        "email_log",
        ["purpose", sa.text("created_at DESC")],
    )

    # ------------------------------------------------------------------
    # 13. Synthetic legacy admin + workspace (ADR 062 §A.2-3)
    # ------------------------------------------------------------------
    op.execute(
        sa.text(
            """
            INSERT INTO users (id, email, password_hash, is_verified, role)
            VALUES (
                gen_random_uuid(),
                'legacy@signalnest.local',
                :sentinel,
                false,
                'admin'
            )
            """
        ).bindparams(sentinel=LEGACY_ADMIN_PASSWORD_SENTINEL)
    )
    op.execute(
        """
        INSERT INTO workspaces (id, slug, name, owner_id, is_demo)
        SELECT
            gen_random_uuid(),
            'signalnest-legacy',
            'SignalNest (legacy)',
            id,
            false
        FROM users
        WHERE email = 'legacy@signalnest.local'
        """
    )

    # ------------------------------------------------------------------
    # 14. feedback_item.workspace_id (nullable; flipped to NOT NULL in
    #     Migration B per ADR 062)
    # ------------------------------------------------------------------
    op.add_column(
        "feedback_item",
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=True,
        ),
    )


def downgrade() -> None:
    # 14. feedback_item.workspace_id
    op.drop_constraint(
        "feedback_item_workspace_id_fkey",
        "feedback_item",
        type_="foreignkey",
    )
    op.drop_column("feedback_item", "workspace_id")

    # 13. Synthetic legacy rows. Workspace first (FK to user), then user.
    op.execute("DELETE FROM workspaces WHERE slug = 'signalnest-legacy'")
    op.execute("DELETE FROM users WHERE email = 'legacy@signalnest.local'")

    # 12. email_log
    op.drop_index("email_log_purpose_idx", table_name="email_log")
    op.drop_index("email_log_status_idx", table_name="email_log")
    op.drop_index("email_log_workspace_idx", table_name="email_log")
    op.execute("DROP TRIGGER IF EXISTS email_log_set_updated_at ON email_log")
    op.drop_table("email_log")

    # 11. auth_rate_limits
    op.drop_table("auth_rate_limits")

    # 10. password_reset_tokens
    op.drop_table("password_reset_tokens")

    # 9. email_verification_tokens
    op.drop_table("email_verification_tokens")

    # 8. sessions
    op.drop_index("sessions_user_id_idx", table_name="sessions")
    op.drop_index("sessions_token_hash_idx", table_name="sessions")
    op.drop_table("sessions")

    # 7. workspace_invitations
    op.drop_index("workspace_invitations_open_idx", table_name="workspace_invitations")
    op.drop_table("workspace_invitations")

    # 6. workspace_memberships
    op.drop_table("workspace_memberships")

    # 5. workspaces
    op.execute("DROP TRIGGER IF EXISTS workspaces_set_updated_at ON workspaces")
    op.drop_table("workspaces")

    # 4. users
    op.execute("DROP TRIGGER IF EXISTS users_set_updated_at ON users")
    op.drop_table("users")

    # 3. Enum extensions: Postgres has no DROP VALUE in stable releases,
    # so the new ``status_enum`` and ``source_enum`` labels stay behind
    # after a downgrade. Documented in ADR 062 — Migration A is reversible
    # in shape only; the extra enum labels are harmless and removed by
    # the eventual v2.1 type-rebuild migration.

    # 2. New enum types
    bind = op.get_bind()
    postgresql.ENUM(name="email_purpose_enum").drop(bind, checkfirst=False)
    postgresql.ENUM(name="email_status_enum").drop(bind, checkfirst=False)
    postgresql.ENUM(name="workspace_role_enum").drop(bind, checkfirst=False)
    postgresql.ENUM(name="user_role_enum").drop(bind, checkfirst=False)

    # 1. citext: leave the extension installed. Other tooling may rely
    # on it; a downgrade should not uninstall a Postgres extension.
