"""v2 Migration B — backfill, NOT NULL flip, rejected → closed rename.

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-06

Hand-authored (not autogenerated). The data half of the v1 → v2
cut-over choreographed by [ADR 062](../../docs/adr/062-v1-to-v2-data-migration.md):

1. Backfill ``feedback_item.workspace_id`` for every legacy row to
   the synthetic ``signalnest-legacy`` workspace inserted by
   Migration A.
2. Pre-flip assertion: zero rows may still have ``workspace_id IS
   NULL``. The migration aborts if any do.
3. ``ALTER COLUMN workspace_id SET NOT NULL``.
4. Rewrite every ``status='rejected'`` row to ``'closed'`` (per
   [ADR 063](../../docs/adr/063-status-enum-extension.md)).
5. ``CHECK (status <> 'rejected')`` so the application can never
   write the deprecated value again.
6. Workspace-scoped indexes on ``feedback_item``.

Migration B is **idempotent** but intentionally **forward-only**:
re-running it from the top is safe (the ``UPDATE``s become no-ops),
but a ``downgrade()`` that re-introduces ``NULL workspace_id`` or
``rejected`` rows would be write-only code. Recovery from a failed
B is via snapshot restore, per the deploy runbook in
``docs/project/spec/v2/rollout.md``.

Hand-review checklist (verified before merge):

- backfill UPDATE is bounded (single small table) and uses the
  legacy workspace id resolved by slug;
- the pre-flip assertion runs in the same transaction as the
  flip;
- the new ``CHECK`` constraint is named consistently with the
  ORM model (``feedback_item_status_not_rejected``);
- every new index has a deterministic name and is created without
  ``CONCURRENTLY`` (single-revision migrations cannot be
  concurrent — see ADR 062 §A.5).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


LEGACY_WORKSPACE_SLUG = "signalnest-legacy"


def upgrade() -> None:
    bind = op.get_bind()

    # ------------------------------------------------------------------
    # 1. Backfill workspace_id for every legacy row.
    # ------------------------------------------------------------------
    op.execute(
        sa.text(
            """
            UPDATE feedback_item
               SET workspace_id = (
                   SELECT id FROM workspaces WHERE slug = :slug
               )
             WHERE workspace_id IS NULL
            """
        ).bindparams(slug=LEGACY_WORKSPACE_SLUG)
    )

    # ------------------------------------------------------------------
    # 2. Pre-flip assertion. Migration B refuses to flip the column to
    #    NOT NULL while any row is still NULL — surfacing the failure
    #    here gives a clearer error than the bare ALTER would.
    # ------------------------------------------------------------------
    remaining = bind.execute(
        sa.text("SELECT count(*) FROM feedback_item WHERE workspace_id IS NULL")
    ).scalar_one()
    if remaining:
        msg = (
            f"Migration B refused to flip feedback_item.workspace_id to "
            f"NOT NULL: {remaining} row(s) still have NULL workspace_id. "
            "Backfill the legacy workspace before re-running."
        )
        raise RuntimeError(msg)

    # ------------------------------------------------------------------
    # 3. Flip workspace_id to NOT NULL.
    # ------------------------------------------------------------------
    op.alter_column(
        "feedback_item",
        "workspace_id",
        existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # 4. Rewrite every legacy ``rejected`` row to ``closed`` (ADR 063).
    # ------------------------------------------------------------------
    op.execute("UPDATE feedback_item SET status = 'closed' WHERE status = 'rejected'")

    # ------------------------------------------------------------------
    # 5. Forbid future writes of ``rejected`` at the database boundary.
    # ------------------------------------------------------------------
    op.create_check_constraint(
        "feedback_item_status_not_rejected",
        "feedback_item",
        "status <> 'rejected'",
    )

    # ------------------------------------------------------------------
    # 6. Workspace-scoped indexes — created on the now-populated column
    #    so the index build runs once on its final shape.
    # ------------------------------------------------------------------
    op.create_index(
        "feedback_workspace_idx",
        "feedback_item",
        ["workspace_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "feedback_workspace_status_idx",
        "feedback_item",
        ["workspace_id", "status"],
    )
    op.create_index(
        "feedback_stale_idx",
        "feedback_item",
        ["workspace_id", "created_at"],
        postgresql_where=sa.text("status IN ('new', 'needs_info')"),
    )


def downgrade() -> None:
    """Schema-only reverse of Migration B.

    Per ADR 062 the data half of B (the ``rejected → closed`` rewrite
    and the ``workspace_id`` backfill) is **forward-only** — recovery
    in production is via snapshot restore, not via ``alembic
    downgrade``. We still ship a *schema* downgrade so the migration
    can be exercised in CI round-trip tests on a controlled snapshot:

    - the workspace-scoped indexes are dropped,
    - the ``status <> 'rejected'`` CHECK is dropped,
    - ``feedback_item.workspace_id`` is set back to NULLABLE.

    Rows that were rewritten from ``rejected → closed`` stay
    ``closed``; rows whose ``workspace_id`` was backfilled keep their
    populated value. Re-running ``alembic upgrade 0003`` after this
    is a no-op for those rows and reasserts the CHECK + NOT NULL.
    """
    op.drop_index("feedback_stale_idx", table_name="feedback_item")
    op.drop_index("feedback_workspace_status_idx", table_name="feedback_item")
    op.drop_index("feedback_workspace_idx", table_name="feedback_item")
    op.drop_constraint(
        "feedback_item_status_not_rejected",
        "feedback_item",
        type_="check",
    )
    op.alter_column(
        "feedback_item",
        "workspace_id",
        existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
        nullable=True,
    )
